# Generated by Django 4.0 on 2023-04-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_alter_cotes_student_alter_student_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField()),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('cotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.cotes')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.student')),
            ],
        ),
    ]
