# Generated by Django 4.0 on 2023-04-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0006_recours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recours',
            old_name='cotes',
            new_name='point',
        ),
    ]
